In [58]:
import numpy as np
import pandas as pd

In [59]:
x1=np.random.randint(1,20,size=(50,))
x2=np.random.randint(1,20,size=(50,))

In [60]:
x1

array([17,  6,  6,  4,  4, 16,  9,  9, 16,  7,  1, 13,  5, 16,  1, 15,  5,
       18, 16, 18, 12, 15, 16,  9, 10, 19,  5, 13,  6, 15, 12, 18, 11,  4,
        7, 12, 18,  4, 11,  8, 10, 13, 14,  2, 19,  9,  2,  8, 12,  9])

In [61]:
x2

array([18,  7,  2,  3,  6, 12,  4, 16, 10, 13,  1,  1, 16,  1, 17,  1, 16,
        3, 17,  5, 18, 13,  6, 15, 10,  5,  5, 15,  4, 19,  5, 14, 19, 12,
        1, 14, 17, 14,  6, 10,  4, 15, 18,  6, 18,  4,  9,  6,  7, 14])

In [62]:
# y=beta0 + beta1*x1 +beta2*x2 .......+betan*xn + e(error)
# y = 3 + 2x1 + 4*x2 + error

In [63]:
y= 3 + 2*x1 + 4*x2 + np.random.random(50)

In [64]:
y

array([109.43652568,  43.95434332,  23.28682671,  23.77939614,
        35.82852234,  83.94842404,  37.75520611,  85.53310333,
        75.72785789,  69.89593436,   9.40884209,  33.97697123,
        77.61420265,  39.66411639,  73.13037352,  37.7463959 ,
        77.91504508,  51.26257156, 103.87898339,  59.63983826,
        99.38028501,  85.97745735,  59.71834654,  81.44659746,
        63.6626597 ,  61.03733053,  33.88827402,  89.04913755,
        31.28117324, 109.13873804,  47.96548011,  95.79973008,
       101.7517797 ,  59.32665329,  21.94262794,  83.66924632,
       107.68899618,  67.54301808,  49.51166274,  59.86165328,
        39.06442784,  89.46944598, 103.04579935,  31.00772683,
       113.83389499,  37.74969067,  43.57186092,  43.8267378 ,
        55.45046036,  77.47892867])

In [65]:
x=pd.DataFrame({"Intercept":np.ones_like(50),'x1':x1,'x2':x2})

In [66]:
x

Intercept  x1  x2
0           1  17  18
1           1   6   7
2           1   6   2
3           1   4   3
4           1   4   6
5           1  16  12
6           1   9   4
7           1   9  16
8           1  16  10
9           1   7  13
10          1   1   1
11          1  13   1
12          1   5  16
13          1  16   1
14          1   1  17
15          1  15   1
16          1   5  16
17          1  18   3
18          1  16  17
19          1  18   5
20          1  12  18
21          1  15  13
22          1  16   6
23          1   9  15
24          1  10  10
25          1  19   5
26          1   5   5
27          1  13  15
28          1   6   4
29          1  15  19
30          1  12   5
31          1  18  14
32          1  11  19
33          1   4  12
34          1   7   1
35          1  12  14
36          1  18  17
37          1   4  14
38          1  11   6
39          1   8  10
40          1  10   4
41          1  13  15
42          1  14  18
43          1   2   6
44          1  19  18
45          1   9   4
46          1   2   9
47          1   8   6
48          1  12   7
49          1   9  14

In [67]:
x.shape

(50, 3)

In [68]:
x.shape[1]

3

In [69]:
w = np.zeros(x.shape[1])

In [70]:
w

array([0., 0., 0.])

In [71]:
def mypredictions(features,weights):
    mypredictions = np.dot(features,weights)
    return(mypredictions)
mypredictions(x,w)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
def myerror(target,features,weights):
    error = target-mypredictions(features,weights)
    return(error)
myerror(y,x,w)

array([109.43652568,  43.95434332,  23.28682671,  23.77939614,
        35.82852234,  83.94842404,  37.75520611,  85.53310333,
        75.72785789,  69.89593436,   9.40884209,  33.97697123,
        77.61420265,  39.66411639,  73.13037352,  37.7463959 ,
        77.91504508,  51.26257156, 103.87898339,  59.63983826,
        99.38028501,  85.97745735,  59.71834654,  81.44659746,
        63.6626597 ,  61.03733053,  33.88827402,  89.04913755,
        31.28117324, 109.13873804,  47.96548011,  95.79973008,
       101.7517797 ,  59.32665329,  21.94262794,  83.66924632,
       107.68899618,  67.54301808,  49.51166274,  59.86165328,
        39.06442784,  89.46944598, 103.04579935,  31.00772683,
       113.83389499,  37.74969067,  43.57186092,  43.8267378 ,
        55.45046036,  77.47892867])

In [73]:
def mycost(target,features,weights):
    error = myerror(target,features,weights)
    cost = np.dot(error.T,error)
    return(cost)
mycost(y,x,w)   

242000.92859017962

In [74]:
def gradient(target,features,weights):
    error = myerror(target,features,weights)
    gradient = -np.dot(features.T,error)
    return(gradient)
gradient(y,x,w)

array([ -3197.52330058, -37343.67421875, -38964.68738255])

In [ ]:
def my_lr(target,features,learning_rate):
    weights=np.zeros(features.shape[1])
    pcf = mycost(target,features,weights)
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=30*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        
        ncf = mycost(target,features,weights)
        if abs(ncf-pcf) < 0.00001:
            break
        if i%100==0:
            print(i,pcf,ncf,weights)
        pcf = ncf
    return(weights)

my_lr(y,x,0.0000001)

0 242000.92859017962 241355.4896416312 [0.00990064 0.00373437 0.00389647]
100 185356.35801159532 184863.56801050718 [0.93454069 0.35204348 0.36898629]
200 142106.64245785528 141730.36435447523 [1.74072738 0.65486811 0.68959691]
300 109080.82387961459 108793.47635666456 [2.44344081 0.91797542 0.97132777]
400 83858.6924239976 83639.22423598949 [3.05576798 1.14640355 1.21907102]
500 64593.03884472226 64425.38275461604 [3.58914204 1.34455373 1.43710086]
600 49873.990598977936 49745.88336224209 [4.05355127 1.51627082 1.62915167]
700 38625.46785585951 38527.549586189765 [4.45772164 1.66491356 1.7984862 ]
800 30026.154674496574 29951.28144451728 [4.80927634 1.79341601 1.94795515]
900 23449.181116262975 23391.900307488057 [5.11487516 1.90434125 2.08004926]
1000 18416.086272043234 18372.236141423316 [5.38033618 1.99992823 2.19694479]
1100 14561.681041231588 14528.085094648108 [5.61074215 2.08213277 2.30054323]
1200 11607.230026715433 11581.463752837726 [5.81053344 2.15266329 2.39250604]
1300 93

10800 234.37870083438094 234.32993092782385 [6.38423832 2.11856432 3.6359002 ]
10900 229.5619102851516 229.5143512551564 [6.37718655 2.11558141 3.63958495]
11000 224.864665978091 224.81828682103034 [6.3701674  2.11264021 3.64322385]
11100 220.28390721356243 220.23867772358005 [6.36318058 2.10974015 3.6468175 ]
11200 215.81665204776527 215.7725427962338 [6.3562258  2.10688071 3.65036648]
11300 211.459995264611 211.41697758011645 [6.34930275 2.10406135 3.65387136]
11400 207.21110639983377 207.169152348675 [6.34241116 2.10128156 3.65733272]
11500 203.0672278159982 203.02631018318934 [6.33555073 2.09854081 3.66075112]
11600 199.02567282709163 198.98576509785622 [6.32872119 2.09583859 3.6641271 ]
11700 195.08382387142225 195.04490021315937 [6.32192225 2.0931744  3.66746122]
11800 191.23913073157146 191.20116597629027 [6.31515363 2.09054773 3.67075402]
11900 187.4891088002051 187.45207842740945 [6.30841507 2.08795811 3.67400603]
12000 183.83133739053096 183.7952175105467 [6.30170628 2.085405

21500 48.3186431482006 48.31443163884306 [5.76953284 1.95607575 3.85653551]
21600 47.90142758316172 47.89729524874922 [5.76479367 1.95549274 3.85754617]
21700 47.492034029009844 47.48797894893418 [5.76006865 1.95491973 3.85854528]
21800 47.09027286037511 47.08629316301407 [5.75535769 1.95435661 3.85953299]
21900 46.6959592878668 46.69205314932491 [5.75066072 1.95380323 3.86050945]
22000 46.30891323371784 46.30507887659874 [5.74597764 1.95325947 3.86147479]
22100 45.928959210626246 45.92519490283658 [5.74130838 1.9527252  3.86242916]
22200 45.55592620371845 45.552230257303535 [5.73665283 1.95220028 3.86337271]
22300 45.18964755555145 45.18601832556058 [5.73201093 1.95168459 3.86430555]
22400 44.82996085407723 44.826396737457365 [5.7273826  1.95117801 3.86522784]
22500 44.476707823488525 44.473207258007484 [5.72276774 1.95068041 3.8661397 ]
22600 44.12973421787963 44.1262956810767 [5.71816628 1.95019167 3.86704127]
22700 43.788889717642064 43.78551172580508 [5.71357814 1.94971168 3.86793